# Generated by Django 4.1.5 on 2023-01-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_testimonial_alter_emp_emp_id_alter_emp_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='picture',
            field=models.ImageField(default=0, upload_to='testimonials/'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='testimonial',
            field=models.TextField(default=0),
        ),
    ]
